### PR TITLE
Fix EternalClass and remove faulty edge handler

### LINKED ISSUE #111: Fix ExternalClasses
### Suggested Changes
Current external classes are a bit ad-hoc, and the relationship between the "class order", namely the prioritazion order between what type of node will be visualized, when different node types are merged. Also, external classes are simply not registered correctly.

### Why Is This Needed?
Required for #96 

### Dependencies
#101

### Documentation Update
--

### LINKED ISSUE #165: Triples in resolved_edge_map are never inserted
### Suggested Changes
Triples for the resolved edge map are never inserted. It's primary use is in try_resolve_unknown_edges(), however nothing is ever inserted, probably an oversight. Hence, all cases in which is matched on (None, _, _) are implicitely true. 
Question however arises, which triple should be inserted? Currently, 3 different relevant triples could be inserted.. The domain, the range, and the object property itself. 

### Documentation Update
Document what triple is stored.

### PR DESCRIPTION
**Pull request by khmikkelsen**
- check for undeclared external classes after serialization.
- remove faulty edge handler.
- fix datafusion debug logs. 

closes #111 
closes #165

### CODE REVIEW

**Review by TheRealMorgenfrue — CHANGES_REQUESTED** [review]

File: crates/database/src/serializers/frontend.rs [hunk 1]
```diff
@@ -936,15 +938,41 @@ impl GraphDisplayDataSolutionSerializer {
         }
     }
 
+    fn check_external_classes(&self, data_buffer: &mut SerializationDataBuffer) {
+        let mut triples_to_add = Vec::new();
+        for (idx, _) in data_buffer.unknown_buffer.iter() {
+            if self.is_external(data_buffer, idx) {
+                // dummy triple, only subject matters.
+                let triple = Triple::new(
+                    Term::NamedNode(NamedNode::new(idx.clone()).unwrap()),
```
Comment (TheRealMorgenfrue) [inline crates/database/src/serializers/frontend.rs]: When running the code, I get a panic:
```
thread 'actix-rt|system:0|arbiter:4' (30145) panicked at crates/database/src/serializers/frontend.rs:947:65:
called `Result::unwrap()` on an `Err` value: IriParseError { kind: InvalidIriCodePoint('<') }
````
We should strip `<>` from the string before making a term of it

**Review by TheRealMorgenfrue — CHANGES_REQUESTED** [review]
