### PR TITLE
Issue237

### LINKED ISSUE #237: Resolving restrictions is order dependent
**Describe the bug**
Changing the ordering of solutions can sometimes fail to resolve restrictions.

### PR DESCRIPTION
**Pull request by nikarnik**
Closes #237

### CODE REVIEW

File: crates/database/src/serializers/frontend.rs [hunk 1]
```diff
@@ -3961,6 +4069,54 @@ impl GraphDisplayDataSolutionSerializer {
...
+                    object_term_id,
+                )? {
+                    Some(edge) => edge,
+                    None => existing_edge,
+                };
+
+                data_buffer
+                    .edge_cardinality_buffer
+                    .write()?
+                    .insert(edge, cardinality);
```
Comment (TheRealMorgenfrue) [inline crates/database/src/serializers/frontend.rs]: We should release the lock before doing the somewhat expensive operations afterwards. This also prevents future problems if those methods ever need a lock to edge_cardinality buffer. 
(the lock is automatically released when going out of scope)
```suggestion
                {
                    data_buffer
                        .edge_cardinality_buffer
                        .write()?
                        .insert(edge, cardinality);
                }
```

**Review by TheRealMorgenfrue — CHANGES_REQUESTED** [review]

**Review by TheRealMorgenfrue — APPROVED** [review]
